### ISSUE TITLE
Setting allowance for a channel

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#107]
Docs: https://docs.openzeppelin.com/contracts/3.x/api/token/erc777#ERC777-allowance-address-address-

```
allowance(address holder, address spender) → uint256
approve(address spender, uint256 value) → bool
```

allowance (get)
 - holder: 
 - spender: 

approve (set)
 - spender: Hopr Channels
 - value: allowance value

**Comment by diegoalzate** [comment]
#### assumptions
- safe is the holder of the tokens

#### questions
- who is the spender that will be able to use these tokens? is there an example flow of this?
- what is the value that safe is going to approve to this spender? max or just enough for a couple channels?
