### ISSUE TITLE
Node screen: node added

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#111]
Definition of done:
- functionality and looks of the component marked with red

https://www.figma.com/file/qjTbRGulmsPBQ2E0aHY7HI/Staking-UI-v3?type=design&node-id=646-2296&mode=design&t=OzWQ4x50iuiMrCHz-0
![image](https://github.com/hoprnet/hopr-admin/assets/104129084/0d688222-a532-4e7a-a05a-69ceb56e9ad9)

**Comment by camilovegag** [comment]
Blocked by #109
