### ISSUE TITLE
Actions subpage

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#137]
Definition of done:
- Combine pending transactions and hisotry into a new page: Actions
- style acordingly with the Figma
- only do the part marked by orange triangle

Figma: https://www.figma.com/file/qjTbRGulmsPBQ2E0aHY7HI/Staking-UI-v3?type=design&node-id=1046-10881&mode=design&t=2cOTotcwZzsvxUy3-0
![image](https://github.com/hoprnet/hopr-admin/assets/104129084/9a51e2ab-5430-429b-b235-a68f182f8f44)

**Comment by diegoalzate** [comment]
![CleanShot 2023-07-25 at 14 38 24](https://github.com/hoprnet/hopr-admin/assets/22416585/bb23e7da-7eb0-4218-a3b4-3969dfc4b784)

I would say that history should not have actions. In theory it already was either executed or rejected.

**Comment by diegoalzate** [comment]
What information should be shown in the VALUE/CURRENCY part of the table if it is a contract interaction that includes no amount being transferred ? null ?

**Comment by diegoalzate** [comment]
There is also the case where there is no source which is when a delegate proposes a transaction, what should we show the user in that case? I was thinking Delegate or Node.

**Comment by mjadach-iv** [comment]
> I would say that history should not have actions. In theory it already was either executed or rejected.

Yes 


> What information should be shown in the VALUE/CURRENCY part of the table if it is a contract interaction that includes no amount being transferred ? null ?

All the calls should invlude something, it could be a value (not coint amount) or a bool.

> There is also the case where there is no source which is when a delegate proposes a transaction, what should we show the user in that case? I was thinking Delegate or Node.

Best to show Delegate ETH address for now
