### ISSUE TITLE
Browser without wallet should not show an empty white page

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-admin#286]
As a user of the Staking Hub, I might not have my EVM wallet extension activated but I want to still be able to see the page so that I can understand what this is about and take the right option (such as in my case opening the correct link in my "wallet" browser profile which is separate from my web browsing profile).

Currently, the page just shows an entirely empty white page without any content when no EVM wallet extension is active.

**Comment by mjadach-iv** [comment]
Fixed
