### ISSUE TITLE
Staking Hub: add "start" button when wallet is connected on home screen

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-admin#321]
after connecting a wallet and clicking "not now" on the popup, a user will have a hard time finding out how to start the onboarding journey. The first big CTA button just reads "wallet connected" and is grayed out. IMO that button should be replaced by "start" or "create Safe" (the latter is probably too technical and requires too much understanding)

**Comment by mjadach-iv** [comment]
Done
