### ISSUE TITLE
fix links to safe.global and onchainden.com

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-admin#326]
1. The links on the `safe` tab for safe.global should link to `https://app.safe.global/home?safe=gno:SAFE_ADDRESS`
2. the link to onchainden are currently having a link to our module and not the Safe in the URL if I'm not mistaken

Both web apps currently don't seem to be able to support HOPR Safes but I pinged both Den and Safe to support us.

**Comment by mjadach-iv** [comment]
@SCBuergel, updated - please test
