### ISSUE TITLE
Admin: WalletConnect

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#36]
Definition of Done:
 - connect through WalletConnect as any other MM compatible wallet
 - have a possibility of signing transations/sefe req. though WalletConnect

**Comment by diegoalzate** [comment]
There are open issues and discussions for this and could not find a solution: https://github.com/wagmi-dev/wagmi/discussions/2582

**Comment by diegoalzate** [comment]
wallet connect does not support safe wallets yet: https://github.com/orgs/WalletConnect/discussions/3417
