### ISSUE TITLE
Admin subpage: Metrics (using getMetrics from the HOPR-SDK)

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#37]
Definition of Done:
 - check if there are ready to use packages to show the data easly
 - show all metris on a Metrics subpage that you can get from getMetrics from the HOPR-SDK

**Comment by diegoalzate** [comment]
current hoprd metrics: https://github.com/hoprnet/hoprnet/blob/master/METRICS.md
