### ISSUE TITLE
Node Admin: Notifications disable

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#413]
Definition of Done:
- Add an option to turn off notifications for all types of notifications ( list of types with swiches next to them)
- It should in the Configuration page
- should be savedto localstorage and redux
- on load of the add, get data  from localstorage and save it to redux

**Comment by diegoalzate** [comment]
@mjadach-iv 

Should this deactivate the fetching or only the push notifications? I think it should only not push notifications but we should still poll the value as it could refresh other ui states.
