### ISSUE TITLE
Admin UI: Drawer on mobile

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#42]
Definition of Done:
- add hamburger to the app-bar
- humberger should show/hide the names of the buttons and it should grow/minimalize the drawer like
- drawer will have 2 states:
![image](https://github.com/hoprnet/hopr-admin/assets/104129084/683a0178-ff71-4ae7-8229-184d4ea12ad9)
- only if the drawer is minimalized, then each icon should have a tooltip on the right with the name of the right
- opened/closing of the drawer  should nicely slide like it is now 
- highlight of the drawer when on a page with hopr blue
- the title of a section should get cut if its too long and ellipsis should be shown

**Comment by mjadach-iv** [comment]
@camilovegag, the task was updated

**Comment by camilovegag** [comment]
I think that removing the subheaders would be better than showing a cropped text @mjadach-iv 

https://github.com/hoprnet/hopr-admin/assets/59750365/d98b302d-2bfe-4b86-9581-adae89f06a3c

**Comment by mjadach-iv** [comment]
The icons have to stay at exactly the same place, if you can do it with removing the subheaders, you can draft a proposal

**Comment by camilovegag** [comment]
Make transition smoother, is there a way to make the paddings between the icon smaller, maybe icons for the groups
