### ISSUE TITLE
Staking balance with long decimal number moves action buttons

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-admin#455]
Issue: when staking number is decimal and it is very long, it moves buttons. This means user can't do any action.
Monitor size doesn't impact much, cause I am experiencing the same issue.

<img width="955" alt="image" src="https://github.com/hoprnet/hopr-admin/assets/73285987/4e133490-6995-4de9-abd6-dc0aa5ac4d69">

**Comment by mjadach-iv** [comment]
Done
