### ISSUE TITLE
Admin UI: Toasts

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-admin#48]
Definition of done:
 - use of Toastify: https://fkhadra.github.io/react-toastify/use-react-toastify-with-redux
 - similar to that: https://codesandbox.io/s/2485wxy78j?from-embed
 - when a new notification is added to Redux, show the toast at the bottom right
 - if multiple notifications come, add new one at the bottom right and move the last one up by one
 - 5s notification time
 - support for all types: info, success, warning, error, default
 - notifications should have 'seen' (instead of read) and 'new' keys in the object
 - if 'x' is clicked on the toast, then 'seen' and 'new' should be true
 - if a notification icon is pressed on the app bar, all the notifications should have be mared as 'new: false'
 - notification that is not 'seen' should have a background highlight of hopr blue with some transparency
 - if you click on the notification in the list in the app bar, it shoud be marked as 'seen: true'
 - the number on the notification bell in the app bar should count the 'new: true' notifications
- add more details on the toast than we have at the appbar dropdown

**Comment by diegoalzate** [comment]
I think we should go for an alternate naming convention:
```JSON
{
  "seen": "boolean" // is true until notification tray is opened, when notification tray is opened all notifications will be seen but not read
  "read": "boolean" // true when notification is clicked
}
```

> notification that is not 'seen' should have a background highlight of hopr blue with some transparency
Right now we stop showing notifications that have been read, if we maintain them then when will the notification tray ever get reduced? It will still show notifications that have been seen and read just with different styles. We can allow it to be ever growing for now but I consider this a possible issue in the future.
