### ISSUE TITLE
Tickets redeeming process

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-admin#480]
**Issue:** After we reduced HOPR price per ticket, nodes are receiving tickets 10 times more. Community members, when they see unredeemed tickets, they are immediately trying to redeem them. This causes issues, cause every ticket is being redeemed separately on chain.

**Solution:** Because we want users to use aggregation instead of redeeming (redeeming function is still needed on admin UI). Whenever user is trying to click on Redeem button, it should popup with a warning:

> Before redeeming tickets, we strongly recommend aggregating them first and waiting for 5 minutes. If the tickets' aggregation does not work, only in this case should you proceed to redeem non-aggregated tickets, which will attempt to redeem every single ticket on the chain. This can be quite expensive. Are you sure you want to proceed?

**Comment by mjadach-iv** [comment]
The ticket redemption was rememver after talks with @Jaguaras
