### ISSUE TITLE
hub.HORPnet.org: inside Dashboard, shorten the amount of digits in order to grant the buttons enough space

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/hopr-admin#508]
PROBLEM
On a 13-inch the long digits do horizontally squish the buttons:
<img width="1440" alt="Bildschirmfoto 2024-01-15 um 21 11 51" src="https://github.com/hoprnet/hopr-admin/assets/78225531/96471e9d-a3e7-4f94-b8ab-cf9b38d057fb">

SOLUTION
shorten the displayed digits

**Comment by mjadach-iv** [comment]
Done
