### ISSUE TITLE
Missing Safe transaction during onboarding process: including the announcement contract as target

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-admin#517]
For users onboarded via Stake Hub UI, user must complete a **Safe** transaction (ideally after "Scope the default permissions for a given HOPR channels contract and the HOPR token in usage"), where the **inner transaction** is
```json
{
  "to": "deployed module address",
  "data": "0xa76c9a2f619eabE23FD0E2291B50a507719aa633fE6069b8010003000000000000000000"
}
```
where `619eabE23FD0E2291B50a507719aa633fE6069b8` is the "announcement" contract address of dufour network

Workflow wise, this step doesn't block any other step, i.e. as long as it's in the onboarding process it's fine.

_Originally posted by @QYuQianchen in https://github.com/hoprnet/hoprnet/issues/5960#issuecomment-1911784509_

**Comment by mjadach-iv** [comment]
HoprNodeManagementModule: scopeTargetToken() (0xa76c9a2f)
