### ISSUE TITLE
Multi node onboarding process issue

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-admin#521]
**Issue:** During the final step of node funding, the new screen with congratulations on adding an additional node does not load, even though the transaction went through, and the node has started

<img width="1800" alt="image" src="https://github.com/hoprnet/hopr-admin/assets/73285987/72857308-bb77-4ef4-b67c-bb742744f607">

**Comment by mjadach-iv** [comment]
Fixed
