### ISSUE TITLE
Reflect checksum from the current API metrics endpoint

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-admin#602]
### Is your feature related to a problem?

This feature will be extremely helpful for quickly checking if the node has synced properly or not.

### Describe the feature you'd like

The HOPRd 2.1.0 version API endpoint already provides the required data for this feature's metrics.

Reflect `hopr_indexer_block_number` & `hopr_indexer_checksum` under `INFO` page.

`hopr_indexer_checksum` - value should be converted from decimal to hexadecimal

For example: 

<img width="1009" alt="image" src="https://github.com/hoprnet/hopr-admin/assets/73285987/04ecb77b-e5a1-453b-8144-029b07045388">

**Comment by mjadach-iv** [comment]
Where exactly can we find the info in the API?
