### ISSUE TITLE
Unable to parse fields on the Metrics page

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-admin#619]
On my local cluster of 2.1.4 nodes, the metrics page sometimes shows results as expected, sometimes now
Metrics works as expected:
![image](https://github.com/user-attachments/assets/8e03c003-ebc5-4915-b752-5a63f3d79a67)
Metrics DOES NOT work as expected:
![image](https://github.com/user-attachments/assets/c41ee675-996d-4d35-9760-2b21ea947db0)

![image](https://github.com/user-attachments/assets/43bc41e9-db95-456f-93ec-c6ccca06e8a0)
![image](https://github.com/user-attachments/assets/63f89335-cc28-4f40-b6fb-c054de3455c4)

Combining with the error returned from the console, it seems like the UI was not able to handle some undefined value.

From my local machine, I see that the metrics object is returned (see below) but when hopr_aggregated_tickets_count and hopr_aggregations_count fields are missing, the UI fails to display metrics

![image](https://github.com/user-attachments/assets/e0ddc064-d253-4563-9433-fa11e3da2abb)

**Comment by mjadach-iv** [comment]
Fixed
