### ISSUE TITLE
During the closure of the incoming payment channel, it incorrectly reports a failure despite successfully closing

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-admin#622]
### Expected behaviour

Trying to close **incoming payment channel** it should close and get notify about a successful closure.

### Current behaviour

Trying to close **incoming payment channel** it gives an error: `Closing of incoming channel 0x1fef61b2c696896ceb9bbd9e8f81b979a5277d1a838247abdefd6b70952d5d3a failed`. But actually it closes this channel.

I've tried via API and I am getting clear response:

```
{
  "channelStatus": "Closed",
  "receipt": "0x467ce8bb56115bf7488e415ef3c956a5c0230dc4ed767f803c45b409f4482425"
}
```

### Reproduce issue

1. Make sure you having `incoming` payment channel
2. Try to close `incoming` payment channel via Admin UI and then try to close another `incoming` payment channel via API

**Comment by mjadach-iv** [comment]
Need to update hopr-sdk for that
